# Feel free to disable non-critical HA parts during devel by commenting out
# Generated in hadk by executing: cd $ANDROID_ROOT; rpm/helpers/add_new_device.sh

Description: Pattern with packages for vision configurations
Name: jolla-configuration-vision
Requires:
- pattern:jolla-hw-adaptation-vision
- pattern:jolla-configuration-sfe

Summary: Jolla Configuration vision

